#baseURL = 'http://hugo-quickstart-template.netlify.com'
baseURL = '/'
languageCode = 'en-us'
title = 'Boring blog'
theme = 'cactus'

contentDir = 'public'

# theme cactus
[markup]
    [params]
        colortheme = "white" # dark, light, white, or classic
        description = "Just a blog for personal interest."
        mainSection = "posts"
        mainSectionTitle = "Writings"
        showAllPostsOnHomePage = false
        postsOnHomePage = 5
#        tagsOverview = true
        tocInline = true
        showProjectsList = false
        projectsUrl = "https://github.com/xxx"
  [[params.social]]
    name = "github"
    link = "https://github.com/marcuswong"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/marcus-wong-194981109/"
  [[params.social]]
    name = "email"
    link = "cswkmab@gmail.com"  # no need for "mailto:" in the head
# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


